// Componente de iconos centralizados
// Exporta todos los iconos usados en la aplicación

import {
  Loader2,
  UserPlus,
  Trash2,
  X,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Settings,
  LogOut,
  User,
  Users,
  Moon,
  Sun,
  Bell,
  Search,
  Menu,
  Home,
  Calendar,
  BarChart,
  FileText,
  HelpCircle,
  AlertCircle,
  Info,
  CheckCircle,
  XCircle,
  Clock,
  Eye,
  EyeOff,
  Edit,
  Share2,
  Download,
  Upload,
  Plus,
  Minus,
  ArrowLeft,
  ArrowRight,
  RefreshCw,
  Filter,
  Copy,
  Mail,
  Phone,
  MapPin,
  Globe,
  Lock,
  Unlock,
  Shield,
  Activity,
  Heart,
  Star,
  Zap,
  TrendingUp,
  TrendingDown,
  MoreVertical,
  MoreHorizontal,
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  userPlus: UserPlus,
  trash: Trash2,
  close: X,
  check: Check,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  settings: Settings,
  logout: LogOut,
  user: User,
  users: Users,
  moon: Moon,
  sun: Sun,
  bell: Bell,
  search: Search,
  menu: Menu,
  home: Home,
  calendar: Calendar,
  chart: BarChart,
  file: FileText,
  help: HelpCircle,
  alert: AlertCircle,
  info: Info,
  success: CheckCircle,
  error: XCircle,
  clock: Clock,
  eye: Eye,
  eyeOff: EyeOff,
  edit: Edit,
  share: Share2,
  download: Download,
  upload: Upload,
  plus: Plus,
  minus: Minus,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  refresh: RefreshCw,
  filter: Filter,
  copy: Copy,
  mail: Mail,
  phone: Phone,
  location: MapPin,
  globe: Globe,
  lock: Lock,
  unlock: Unlock,
  shield: Shield,
  activity: Activity,
  heart: Heart,
  star: Star,
  zap: Zap,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  moreVertical: MoreVertical,
  moreHorizontal: MoreHorizontal,
}

export type Icon = keyof typeof Icons